#!/bin/bash  
# Force Bash, so we have 'let' for addition 

VERSION="0.01"

echo "If you knew Time as well as I do, said the Hatter, you wouldn't talk about wasting IT. It's HIM."

count=` cat .count `
let count=count+1
echo $count > .count

prefix=` echo $count | awk '{printf("%04d",$1)}' `

echo "OK; going to bundle & rename to (please enter...):"
echo -n "${prefix}-"
read suffix

newdir="${prefix}-${suffix}"

echo "Moving files to ${newdir}..."
mkdir "${newdir}"
mv *.* "${newdir}"

echo "Leaving breadcrumbs..."
crumb="${newdir}/`date +%Y-%m-%d_%H%S`_${USER}_at_${HOSTNAME}"

touch "${crumb}"

cat > ${crumb} << EOF
#Archived with Freck Version ${VERSION}... 
# Still not able to extract history
pwd: ` pwd `
date: ` date `
hostname: `hostname `
EOF

# Doesn't work currently - we're in a sub shell (~:
# Nice things to do with permanently changing .bashrc to adjust history defaults, which might be an idea anyway...
#   HISTFILE="${newdir}"/`date +%Y-%m-%d`_${USER}_at_${HOSTNAME}.dat
#   history -a # Dump history saved in memory (i.e. this shell)

