#!/bin/sh

for file 
do
 HOMO=` grep "occ" "${file}" | tail -n 1 | awk '{print $NF*27.211}' `
 LUMO=` grep "virt" "${file}" | head -n 1 | awk '{print $5*27.211}' `
 KSGAP=` echo "${LUMO} - ${HOMO}" | bc -l `

 echo "${file}  HOMO: ${HOMO} LUMO: ${LUMO} KSGAP: ${KSGAP}"
done
