#!/bin/sh

#Gaussian Log files: Eigenvalues (Hartrees) are fields 5...9 inclusive

for file in "$@"
do
 echo -n "${file} "
 grep "occ" "${file}" | tail -n 1 | awk '{printf("\t\tHOMO: %f\t",$NF*27.211)}'
 grep "virt" "${file}" | head -n 1 | awk '{print "Unocc: ",$5*27.211,$6*27.211,$7*27.211,$8*27.211,$9*27.211, " eV"}'
done
