#!/bin/sh

#PBS -N Disconvergent 
#PBS -l walltime=71:58:00
#PBS -l select=1:ncpus=24:mem=48GB

#PBS -q pqawalsh

module load intel-suite mpi

cp $PBS_O_WORKDIR/* $TMPDIR

# /home/jmf02/bin/vasp_gam          /home/jmf02/bin/vasp_ncl         /home/jmf02/bin/vasp_std
pbsexec mpiexec ~/bin/vasp_ncl > vasp.stdout 

##copy back
cp $TMPDIR/* $PBS_O_WORKDIR

echo "For us, there is only the trying. The rest is not our business. ~T.S.Eliot"

